server:
  port: 8080
  servlet:
    context-path: /acquisition
spring:
  application:
    name: acquisition-service
  cloud:
    nacos:
      server-addr: localhost:8848
      discovery:
        namespace: 9aae8ce7-f7bc-4167-9fdf-234082701131
        group: data-center-group
  datasource:
#    driver-class-name: dm.jdbc.driver.DmDriver
#    url: jdbc:dm://localhost:5236/DATA?zeroDateTimeBehavior=convertToNull&useUnicode=true&characterEncoding=utf-8
#    username: SYSAUDITOR
#    password: SYSAUDITOR
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/a?useSSL=true&useUnicode=true&cerEncoding=utf8
    username: root
    password: 123456

#MyBatis-plus
mybatis-plus:
  configuration:
    # 这个配置会将执行的sql打印出来，在开发或测试的时候可以用
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      table-underline: true
  mapper-locations: classpath*:com/data/center/mapper/xml/*Mapper.xml
  type-aliases-package: com.data.center.domain.Do



