server:
  port: 10010 #网关端口
spring:
  application:
    name: api-gateway #服务名称
  cloud:
    nacos:
      server-addr: localhost:8848
      discovery:
        namespace: 9aae8ce7-f7bc-4167-9fdf-234082701131
        group: data-center-group
    gateway:
#      discovery:
#        locator:
#          enabled: true #启动自动识别nacos服务
      routes: # 网关路由配置
        - id: test-service
          uri: lb://test-service
          predicates:
            - Path=/test-service/**
          filters:
            - RewritePath=/test-service(?<segment>/?.*), /test$\{segment}
      globalcors:
        add-to-simple-url-handler-mapping: true
        cors-configurations:
          '[/**]':
            allowedOrigins:
              - "http://localhost:8080"
              - "http://localhost:10010"
            allowedMethods:
              - "GET"
              - "POST"
              - "DELETE"
              - "PUT"
              - "OPTIONS"
            allowedHeaders: "*"
            allowCredentials: true
            maxAge: 360000