server:
  port: 8080
  servlet:
    context-path: /test
spring:
  application:
    name: test-service
  cloud:
    nacos:
      server-addr: localhost:8848
      discovery:
        namespace: 9aae8ce7-f7bc-4167-9fdf-234082701131
        group: data-center-group
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/niuke?useSSL=true&useUnicode=true&cerEncoding=utf8
    username: root
    password: 123456
  data:
    redis:
      host: 127.0.0.1
      port: 6379
      database: 0



connection:
  pool:
    driver: dm.jdbc.driver.DmDriver
    url: jdbc:dm://localhost:5236/DATA?zeroDateTimeBehavior=convertToNull&useUnicode=true&characterEncoding=utf-8
    username: SYSDBA
    password: SYSDBA
    initSize: 3
    maxSize: 10
    timeout: 10000



