server:
  port: 8090
  servlet:
    context-path: /share
spring:
  application:
    name: share-server
  cloud:
    nacos:
      server-addr: 127.0.0.1:8848
      discovery:
        group: data-center-group
        namespace: 9aae8ce7-f7bc-4167-9fdf-234082701131
  datasource:
    primary:
      driver-class: dm.jdbc.driver.DmDriver
      jdbc-url: jdbc:dm://127.0.0.1:5236/data_center_analysis?zeroDateTimeBehavior=convertToNull&useUnicode=true&characterEncoding=utf-8
      username: SYSDBA
      password: SYSDBA
    secondary:
      driver-class: dm.jdbc.driver.DmDriver
      jdbc-url: jdbc:dm://127.0.0.1:5236/data_center_share?zeroDateTimeBehavior=convertToNull&useUnicode=true&characterEncoding=utf-8
      username: SYSDBA
      password: SYSDBA
  data:
    redis:
      host: 127.0.0.1
      port: 6379
      database: 0

springdoc:
  swagger-ui:
    path: /swagger-ui.html

logging:
  level:
    com.hexadecimal: debug
    # feign日志以什么级别监控哪个接口
    com.gzl.cn.service.PaymentFeignService: debug

#MyBatis-plus
mybatis-plus:
  configuration:
    # 这个配置会将执行的sql打印出来，在开发或测试的时候可以用
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      table-underline: true
  mapper-locations: classpath*:com/data/center/mapper/xml/*Mapper.xml
  type-aliases-package: com.data.center.pojo.Do


#connection:
#  pool:
#    driver: dm.jdbc.driver.DmDriver
#    url: jdbc:dm://10.4.53.14:5236/data_center_analysis?zeroDateTimeBehavior=convertToNull&useUnicode=true&characterEncoding=utf-8
#    username: SYSDBA
#    password: SYSDBA
#    initSize: 3
#    maxSize: 10
#    timeout: 10000



